### ISSUE TITLE
No support for several comment prefixes

### ISSUE THREAD

**Issue by clembu** [MarioZ/MadMilkman.Ini#15]
Hi.

I'm working with a third-party app working with user-provided ini files (meaning that the files I'm gonna parse and edit can come from virtually anyone) so I can't use a custom convention, I have to follow the app's parser behavior.

It happens that this app considers any line that doesn't start with an identifier (key or section) as a comment. Results are that those lines are all valid comments:

```
# Hash
; semi-colon
: colon
// c-style comment
```

But in this app, a valid key identifier is `@include`, meaning that it's not simply a matter of initial character, there's a story about parsing for an identifier.

How does MadMilkman.Ini's comment parsing works?
I can't tell from out of the box, but it surely doesn't parse my colon comment line (though it successfully parses all the others, so there's that).

How could I tell it to consider all those lines valid comments?
Or how could I tell it that `@include` is a valid key identifier?

Thanks.

**Comment by MarioZ** [comment]
Hi,

MadMilkman.Ini will parse all lines that start with comment starter character as trailing comments. By default the comment starter character is ';', but this can be changed by specifying different character in `IniOptions.IniCommentStarter` and then providing that `IniOptions` to `IniFile`'s constructor.

However as it is now I'm afraid only a single comment starter character can be defined. In the future I could consider providing a capability for defining multiple comment starter characters, but I'm presuming it could get rather tricky or better said unfriendly due to leading comments support.
For example:

``` cfg
; This is a trailing comment.
; This is a trailing comment.
key1=value1 ; This is a leading comment.
```

Because multiple characters would then indicate the start of the leading comment, any key's value that has any of those characters will need to be quoted.

Now regarding your requirement, a solution that comes to my mind is to provide a reader adapter that would adjust the lines to `MadMilkman.Ini`'s expectations.
I presume that all your sections start with '[' and all your keys start with '@', so for that here is an example of `IniReaderAdapter`:

``` csharp
public sealed class IniReaderAdapter : TextReader
{
    private readonly TextReader reader;

    public IniReaderAdapter(string path) { this.reader = File.OpenText(path); }

    public override string ReadToEnd()
    {
        string[] content = this.reader.ReadToEnd().Split(new string[] { Environment.NewLine }, StringSplitOptions.None);

        for (int i = 0; i < content.Length; ++i)
        {
            string line = content[i];

            // In order to identify an INI key it must have a key-value delimiter character, which by default is '=' character.
            // So in case we have the following line:
            //
            // @include
            //
            // We must add '=' in order for it to be parsed as key-value pair (with an empty value part).
            if (line.StartsWith("@") && !line.Contains("="))
                content[i] = line + "=";

            // Any line that doesn't start with an identifier (key or section) is a comment.
            else if (!line.StartsWith("[") && !line.StartsWith("@"))
                content[i] = ";" + line;
        }

        return string.Join(Environment.NewLine, content);
    }

    protected override void Dispose(bool disposing) { this.reader.Dispose(); }
}
```

Also here is an example of how to use it:

``` csharp
class Program
{
    static void Main(string[] args)
    {
        IniFile ini = new IniFile();
        using (var reader = new IniReaderAdapter("Sample.ini"))
            ini.Load(reader);

        foreach (IniKey key in ini.Sections[0].Keys)
        {
            Console.WriteLine("KEY NAME: {0}, VALUE: {1}", key.Name, key.Value);
            Console.WriteLine("KEY COMMENT:");
            Console.WriteLine(key.TrailingComment.Text);
            Console.WriteLine();
        }
    }
}
```

The "Sample.ini" I used for testing contains the following content:

``` cfg
# Hash comment and
; semi-colon comment!
@include1
: Colon comment and
// c-style comment!
@include2
```

This content results to the following `Program`'s output:

```
KEY NAME: @include1, VALUE: 
KEY COMMENT:
# Hash comment and
; semi-colon comment!
KEY NAME: @include2, VALUE: 
KEY COMMENT:
: Colon comment and
// c-style comment!
```

I hope this helps.

**Comment by clembu** [comment]
The ReaderAdapter solution would be suitable. Not all of my keys begin with an `@` so I won't use this exact code, but thanks for the solution!
"If the parser doesn't read a comment, make it look like a comment", clever.

Thanks, I'll work with that.
