### ISSUE TITLE
Multiple sections with the same name

### ISSUE THREAD

**Issue by elpatron68** [MarioZ/MadMilkman.Ini#18]
Hi,

I have to deal with a 3rd party INI file that has multiple section of the same name but different keys inside. I haven´t seen a way to handle this case with MadMilkman.Ini, or am I wrong? I think I have to find my own approach, but if anybody has an idea, I would be greatful!

Example:

```
[DriveLetters]
DeviceID=1234567890
Letters=A

[DriveLetters]
DeviceID=0987654321
Letters=B


```

**Comment by MarioZ** [comment]
Hi,

By default MadMilkman.Ini does support section and key duplicates.
Now in order to access those duplicate sections you'll need to use integer indexer instead of string indexer because with the second one you'll only be able to access the first "DriveLetters" section that occurs in the provided input.

In other words, try the following example:
``` csharp
string iniContent =
@"[DriveLetters]
DeviceID=1234567890
Letters=A

[DriveLetters]
DeviceID=0987654321
Letters=B";

IniFile ini = new IniFile();
// Load that above INI content, or you could just load an INI file or an INI stream.
ini.Load(new StringReader(iniContent));

// Get first section, it contains "DeviceID=1234567890" and "Letters=A" keys.
IniSection section1 = ini.Sections[0];

// Get "DeviceID" value:
Console.WriteLine(section1.Keys["DeviceID"].Value);
// Or you can also use this:
//Console.WriteLine(section1.Keys[0].Value);

// Get second section, it contains "DeviceID=0987654321" and "Letters=B" keys.
IniSection section2 = ini.Sections[1];

// Get "DeviceID" value:
Console.WriteLine(section2.Keys["DeviceID"].Value);
// Or you can also use this:
//Console.WriteLine(section2.Keys[0].Value);
```
Also here is another example that demonstrates how you can iterate through INI's content and retrieve the desired information (I used Where extension method from System.Linq).
``` csharp
string iniContent =
@"[DriveLetters]
DeviceID=1234567890
Letters=A

[DriveLetters]
DeviceID=0987654321
Letters=B";

IniFile ini = new IniFile();
ini.Load(new StringReader(iniContent));

// Iterate through INI's content and write the required values.
foreach (IniSection section in ini.Sections.Where(s => s.Name == "DriveLetters"))
    foreach (IniKey key in section.Keys.Where(k => k.Name == "DeviceID"))
        Console.WriteLine(key.Value);
```
Last just in case you're interested, there is also another indexer which accepts targeting multiple names, for example:
``` csharp
string iniContent =
@"[DriveLetters]
DeviceID=1234567890
Letters=A

[DriveLetters]
DeviceID=0987654321
Letters=B";

IniFile ini = new IniFile();
ini.Load(new StringReader(iniContent));
            
IEnumerable<IniSection> driverLetters = ini.Sections["DriveLetters", "DriveLetters", "DriveLetters"];
foreach (IniSection section in driverLetters)
{
    if (section != null)
        Console.WriteLine(section.Keys["DeviceID"].Value);
}
```
Notice that here I'm targeting three "DriveLetters" sections, but the input INI content has only two "DriveLetters" sections and thus the last retrieved `IniSection` is `null`.
Nevertheless, I believe the second example is the one that you require.

I hope this helps, let me know if you need anything else.

**Comment by elpatron68** [comment]
Hi @MarioZ 
thank you so much for help, this made my day!
