### ISSUE TITLE
Merging sample

### ISSUE THREAD

**Issue by js69** [MarioZ/MadMilkman.Ini#19]
Hi,

could you please create a short sample of how to merge two .ini files? I am specifically interested to find out how to merge two .ini files with the same sections and keys. Which values will be used for which IniOptions property settings.

cheers,
JS

**Comment by MarioZ** [comment]
Hi,

Let's say we have the following two INI files.
* _Sample1.ini:_
  ``` cfg
  [Section1]
  key1=value1
  key2=value2
  ```
* _Sample2.ini:_
  ``` cfg
  [Section1]
  key1=value1
  key3=value3
  key5=value5
  ```
In order to merge them we just need to use `Load` method for each file.  
By default MadMilkman.Ini allows duplicate sections and keys.  
In other words:
``` csharp
// The following:
IniOptions options = new IniOptions();
options.SectionDuplicate = IniDuplication.Allowed;
options.KeyDuplicate = IniDuplication.Allowed;
IniFile ini = new IniFile(options);

// Will give us the same behaviour as the following:
IniFile ini = new IniFile();
```

<br />

Now try the following example:
``` csharp
IniFile ini = new IniFile();
ini.Load("Sample1.ini");
ini.Load("Sample2.ini");

foreach (IniSection section in ini.Sections)
{
    Console.WriteLine("SECTION = {0}", section.Name);
    foreach (IniKey key in section.Keys)
        Console.WriteLine("KEY = {0} | VALUE = {1}", key.Name, key.Value);
    Console.WriteLine();
}
```
The console's output will be (notice that both files content is loaded into an `IniFile`, one after another):
```
SECTION = Section1
KEY = key1 | VALUE = value1
KEY = key2 | VALUE = value2

SECTION = Section1
KEY = key1 | VALUE = value1
KEY = key3 | VALUE = value3
KEY = key5 | VALUE = value5
```
But if you use the following option:
``` csharp
IniOptions options = new IniOptions();
options.SectionDuplicate = IniDuplication.Ignored;
IniFile ini = new IniFile(options);
// ...
```
The console's output will be (notice that the second file's content, a section with a duplicate name, is ignored):
```
SECTION = Section1
KEY = key1 | VALUE = value1
KEY = key2 | VALUE = value2
```
Last, MadMilkman.Ini currently does not have something like `IniDuplication.Overridden`, let me know if you need a support for it.

I hope this helps.

**Comment by MarioZ** [comment]
Hi,

I presume that the above example is enough for you so I'll close this ticket.
But in case it's not or in case you have some other question, please let me know.

Regards,
Mario

**Comment by js69** [comment]
Yes, thanks a lot. I'll let you know if I find a need for an Override option.

cheers,
JS

**Comment by js69** [comment]
Sorry, having to reopen this.

I would have expected the example above

IniFile ini = new IniFile();
ini.Load("Sample1.ini");
ini.Load("Sample2.ini");
ini.Save("SampleMerged.ini");

to actually merge the items from same-named sections into one section, with a result like this:

```
[Section1]
key1=value1
key2=value2
key3=value3
key5=value5

```

Is there an easier way to achieve this than writing a "join"-Method on my own?

**Comment by MarioZ** [comment]
Hi,

The problem I find with this is, what to do with the same-named key in the same-named section?
In other words, for the above example what should be done for "key1" that comes from "Sample2.ini" file?

At the top of my head, I feel that the intuitive thing would be to join those keys as well (because we're joining sections), resulting in something like the following:
``` cfg
[Section1]
key1={value1,value1}
key2=value2
key3=value3
key5=value5
```
However, now the question is what should be done with the comments of those "key1" keys?
Well I guess one solution would be to concatenate them, but I'm not sure about this... 
 
Nevertheless, I'm thinking that this could be specified with something like `IniDuplication.Merged`, but currently I would like to postpone this implementation and think about it some more in the future.

For now would you be willing to use the following extension method:
``` csharp
public static class MadMilkmanHelper
{
    public static void Join(this IniFile destination, string path)
    {
        IniFile source = new IniFile();
        source.Load(path);

        foreach (IniSection sourceSection in source.Sections)
        {
            IniSection destinationSection = destination.Sections[sourceSection.Name];
            if (destinationSection == null)
                destination.Sections.Add(sourceSection.Copy(destination));
            else
            {
                foreach (IniKey sourceKey in sourceSection.Keys)
                {
                    IniKey destinationKey = destinationSection.Keys[sourceKey.Name];
                    if (destinationKey == null)
                        destinationSection.Keys.Add(sourceKey.Copy(destination));
                    // TODO: At the moment I'm not sure what to do in this case, when the same key already exists.
                    else { }
                }
            }
        }
    }
}
```
When using it, as demonstrated in the following example, you'll get the expected "SampleMerged.ini" file that you mentioned above:
``` csharp
IniFile ini = new IniFile();
ini.Load("Sample1.ini");
ini.Join("Sample2.ini");
ini.Save("SampleMerged.ini");
```
I hope this works for you.

Regards,
Mario

**Comment by js69** [comment]
Thanks a lot! Can be closed now.
