### ISSUE TITLE
Keys.count produces a Hex value 

### ISSUE THREAD

**Issue by JohnDovey** [MarioZ/MadMilkman.Ini#33]
In `VB.Net` I get an error when trying to count the key values for a specific section. It gives a Hex value.

Here is the code snippet for getting the keys when I supply a section name

``` vb.net
Sub getMsgKeys2(SectionName As String)
        Console.WriteLine("Start getMsgKeys2")
        Dim iniFile As New Ini.IniFile(
                New Ini.IniOptions() With {
                    .CommentStarter = Ini.IniCommentStarter.Semicolon,
                    .KeyDelimiter = Ini.IniKeyDelimiter.Colon,
                    .KeySpaceAroundDelimiter = False,
                    .SectionWrapper = Ini.IniSectionWrapper.SquareBrackets})

        ' Load file from path.
        iniFile.Load("C:\Users\john\source\repos\Sbmr\tmp\ELGATO\HEADERS.DAT")
        Dim KeysCount As Integer = iniFile.Sections(SectionName).Keys.Count

        SBMRMain.RichTextBox1.Text = "Keys for " & SectionName & vbCrLf
        For x As Integer = 0 To KeysCount

            Console.WriteLine("Key- Name: {0}, Value: {1}, Count: {2} ", iniFile.Sections(SectionName).Keys(x).Name, iniFile.Sections(SectionName).Keys(x).Value, x)
        Next
        Console.WriteLine("End getMsgKeys2")
    End Sub
```

There are 24 keys in the file. Works perfectly for x = 0 to x = 23, as expected, then the value generates an out of range exception for the last value which is a Hex value

`iniFile.Sections(SectionName).Keys.Count = &H00000018`

Here is a chunk of my my "ini" file

``` in file
[80]
Utf8 = false
Message-ID: <603D6C87.3345.dove-gen@bbses.info>
In-Reply-To: <603C63B6.1148.dove-general@elgato.synchronetbbs.org>
WhenWritten:  20210301163655-0600  4168
WhenImported: 20210301224012-0500  412c
WhenExported: 20210302044053Z      412c
ExportedFrom: ELGATO dove-general 1176
Sender: MRO
SenderNetAddr: VERT/BBSESINF
SenderIpAddr: 75.86.38.247
SenderHostName: cpe-75-86-38-247.wi.res.rr.com
SenderProtocol: Telnet
Organization: bbses.info
Subject: Re: GAB
To: Boondock
X-FTN-PID: Synchronet 3.18b-Win32  Sep 20 2020 MSC 1927
X-FTN-CHRS: CP437 2
Editor: FSEditor.js v1.104
WhenImported: 20210301143755-0800  41e0
WhenExported: 20210301144013-0800  41e0
ExportedFrom: VERT dove-gen 117335
WhenImported: 20210301163655-0600  4168
WhenExported: 20210301163751-0600  4168
ExportedFrom: BBSESINF dove-gen 3345
Conference: 2001

[380]
Utf8 = false
Message-ID: <603D6CB2.3346.dove-gen@bbses.info>
In-Reply-To: <603CADAA.21222.dove-general@palantirbbs.ddns.net>
WhenWritten:  20210301163738-0600  4168
WhenImported: 20210301224012-0500  412c
WhenExported: 20210302044053Z      412c
ExportedFrom: ELGATO dove-general 1177
Sender: MRO
SenderNetAddr: VERT/BBSESINF
SenderIpAddr: 75.86.38.247
SenderHostName: cpe-75-86-38-247.wi.res.rr.com
SenderProtocol: Telnet
Organization: bbses.info
Subject: Re: GAB
To: Arelor
X-FTN-PID: Synchronet 3.18b-Win32  Sep 20 2020 MSC 1927
X-FTN-CHRS: CP437 2
Editor: FSEditor.js v1.104
WhenImported: 20210301143755-0800  41e0
WhenExported: 20210301144013-0800  41e0
ExportedFrom: VERT dove-gen 117336
WhenImported: 20210301163738-0600  4168
WhenExported: 20210301163751-0600  4168
ExportedFrom: BBSESINF dove-gen 3346
Conference: 2001

```
--- Continues after this ---

The only thing I can think of is the empty line between the last key value and the next section header...

**Comment by JohnDovey** [comment]
![Screen Capture](https://user-images.githubusercontent.com/11061221/110021095-5386aa00-7cf8-11eb-9b0f-10856298c129.png)

**Comment by MarioZ** [comment]
Hi,

When the exception occurs, the state of some members is not stable.
Depending on the framework, platform, you can get different things.

But regardless, the exception occurred which indicates that some action was wrong.
In this case, the problem is that you're trying to access an element that doesn't exist, you're trying to access the 25th element but there are only 24.

So in short, use this instead:

```vb
For x As Integer = 0 To KeysCount - 1
```

Does this solve your issue?

Also just to check, I'm not sure if you did this on purpose, but the first key (_Utf8 = false_) has '=' delimiter while the rest of the keys have ':' delimiter.
This is why the first key is not read, it's ignored.

Regards,
Mario

**Comment by JohnDovey** [comment]
> In this case, the problem is that you're trying to access an element that doesn't exist, you're trying to access the 25th element but there are only 24.
> 
> So in short, use this instead:
> 
> ```vbnet
> For x As Integer = 0 To KeysCount - 1
> ```

> Does this solve your issue?

No. The issue is NOT the loop, but the count. The loop is there to demonstrate the problem with the count. 

The line `Dim KeysCount As Integer = iniFile.Sections(SectionName).Keys.Count` should always return an integer, irrespective of it's value, not a Hex value.

> 
> Also just to check, I'm not sure if you did this on purpose, but the first key (_Utf8 = false_) has '=' delimiter while the rest of the keys have ':' delimiter.
> This is why the first key is not read, it's ignored.
Not done on purpose, but good point and good to know, thank you.

**Comment by MarioZ** [comment]
I'm sorry to say John that I don't know how to explain this differently to you...
The issue is with your code, it has a bug, that much should be clear to you because an exception occurs...

May I suggest something, try placing a breakpoint before the loop and then check the Count value each time your loop iterates.
What value does it show before the exception?

Anyway, just try to listen to me for a second and humor me... do what I suggested, does it work?

Both `Sections` and `Keys` are implemented as List objects, so what you're saying is that List.Count has a problem.
But it really doesn't and I'm afraid I'm not sure how to clear your confusion here...

Perhaps you should take a look at [For...Next](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/for-next-statement) documentation.
This is the first example that's shown in it:
```vb
For index As Integer = 1 To 5
    Debug.Write(index.ToString & " ")
Next
Debug.WriteLine("")
' Output: 1 2 3 4 5
```

In your case, the `index` is 0, e.g.:
```vb
For index As Integer = 0 To 5
```
The output will be: 0 1 2 3 4 5
If you count that you'll notice that those are 6 values.

So, when you do this:
```vb
For x As Integer = 0 To KeysCount
```
It will not go from 0 to 23, it will go from 0 to 24.
That is why you need to use what I suggested.

**Comment by JohnDovey** [comment]
Got it. Thank you, you're correct
